# Generated by Django 4.2.7 on 2024-08-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='stripe_session_id',
        ),
    ]
